#!/bin/bash

FILES=$(grep ".*\.js$" <<< $@)
if [[ -z "$FILES" ]]; then
  exit 0
fi

if ! hash jscs 2>/dev/null; then
  echo "\`jscs\` not installed or not on path" 1>&2
  echo "Please run \`npm install -g jscs\`" 1>&2
  exit 1
fi

$jscs --config "$ROOT_DIR/JavaScript/.jscs.json" $FILES

if [[ $? != 0 ]]; then
  exit 1
fi
