#!/bin/sh

jshint=$(which jshint)
if [ $? -ne 0 ]; then
	echo "jshint not installed or not on path" 1>&2
	exit 1
fi

for file in $@; do
	if [ "${file##*.}" = "js" ]; then
		$jshint --config "$ROOT_DIR/JavaScript/.jshintrc" $file

		if [ $? -ne 0 ]; then
			exit 1
		fi
	fi
done
