#!/bin/bash

if ! hash pep8 2>/dev/null; then
  echo "\`pep8\` not installed or not on path" 1>&2
  echo "Please run \`pip install pep8\`" 1>&2
  exit 1
fi

FILES=$(printf "%s\n" $@ | grep ".*\.py$")
if [[ -n $FILES ]]; then
  $pep8 --config "$ROOT_DIR/Python/pep8" $FILES

  if [[ $? != 0 ]]; then
    exit 1
  fi
fi
