#!/bin/sh

pep8=$(which pep8)
if [ $? -ne 0 ]; then
	echo "\`pep8\` not installed or not on path" 1>&2
	echo "Please run \`pip install pep8\`" 1>&2
	exit 1
fi

FILES=$(printf "%s\n" $@ | grep ".*\.py$")
if [ -n "$FILES" ]; then
	$pep8 --config "$ROOT_DIR/Python/setup.cfg" $FILES

	if [ $? -ne 0 ]; then
		exit 1
	fi
fi
