#!/bin/bash

pylint=$(which pylint)
if [ $? -ne 0 ]; then
  echo "\`pylint\` not installed or not on path" 1>&2
  echo "Please run \`pip install pylint\`" 1>&2
  exit 1
fi

# we need to run pylint on all files, because has certain "global"
# checks that we want to know about
FILES=$(git ls-files | grep ".*\.py$")
if [ -n "$FILES" ]; then
  $pylint --rcfile "$ROOT_DIR/Python/pylintrc" $FILES

  # see `pylint --long-help` for info on these exit codes
  if [[ $(($? & 1)) > 0 || $(($? & 2)) > 0 || $(($? & 16)) > 0 ]]; then
    exit 1
  fi
fi
