#!/bin/sh

scsslint=$(which scss-lint)
if [ $? -ne 0 ]; then
	echo "\`scss-lint\` not installed or not on path" 1>&2
	echo "Please run \`gem install scss-lint\`" 1>&2
	exit 1
fi

for file in $@; do
	if [ "${file##*.}" = "scss" ]; then
		$scsslint --config "$ROOT_DIR/SCSS/.scss-lint.yml" $file

		if [ $? -ne 0 ]; then
			exit 1
		fi
	fi
done
